#!/bin/bash

echo ""
echo "==========================================="
echo "  WEB SERVER DEMO - SETUP & RUN"
echo "==========================================="
echo ""
echo "Step 1: Import database SQL file"
echo ""
echo "- Open MySQL: mysql -u root -p"
echo "- Run: source database.sql"
echo "- Or paste commands from database.sql"
echo ""
echo "Step 2: Start PHP Server"
echo ""
php -S localhost:8000
echo ""
echo "Step 3: Open Browser"
echo ""
echo "- Go to: http://localhost:8000/login.php"
echo ""
echo "Demo Credentials:"
echo "- User: user, Pass: pass"
echo "- User: admin, Pass: admin123"
echo "- User: test, Pass: test123"
echo ""
